<?php

namespace App\Models;

use Database\Factories\UserFactory;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

#[Fillable([
    'name',
    'email',
    'password',
    'generated_posts_count',
    'credit_balance',
    'stripe_customer_id',
    'stripe_subscription_id',
    'stripe_price_id',
    'subscription_status',
    'subscription_plan',
    'subscription_ends_at',
])]
#[Hidden(['password', 'remember_token'])]
class User extends Authenticatable implements MustVerifyEmail
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable;

    /**
     * Get the posts generated by the user.
     */
    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }

    /**
     * Get the Stripe-backed credit pack purchases made by the user.
     */
    public function creditPurchases(): HasMany
    {
        return $this->hasMany(CreditPurchase::class);
    }

    /**
     * Determine whether the user currently has paid access.
     */
    public function hasActiveSubscription(): bool
    {
        return in_array((string) $this->subscription_status, ['active', 'trialing'], true);
    }

    /**
     * Determine whether this account bypasses the standard generation quota.
     */
    public function hasUnlimitedGenerationAccess(): bool
    {
        return strcasecmp(trim((string) $this->name), 'admin') === 0;
    }

    /**
     * Determine whether the user can still generate articles.
     */
    public function canGeneratePosts(): bool
    {
        return $this->hasUnlimitedGenerationAccess()
            || $this->hasActiveSubscription()
            || $this->freeGenerationsRemaining() > 0
            || $this->creditBalance() > 0;
    }

    /**
     * Determine whether the user has exhausted the free quota.
     */
    public function hasReachedGenerationLimit(): bool
    {
        return ! $this->hasUnlimitedGenerationAccess()
            && ! $this->hasActiveSubscription()
            && $this->freeGenerationsRemaining() === 0
            && $this->creditBalance() === 0;
    }

    /**
     * Return the configured free generation limit.
     */
    public function freeGenerationLimit(): int
    {
        return max(0, (int) config('billing.free_generations', 5));
    }

    /**
     * Return the number of free generations remaining.
     */
    public function freeGenerationsRemaining(): int
    {
        return max(0, $this->freeGenerationLimit() - max(0, (int) $this->generated_posts_count));
    }

    /**
     * Return the number of paid article credits remaining.
     */
    public function creditBalance(): int
    {
        return max(0, (int) $this->credit_balance);
    }

    /**
     * Determine whether a paid credit should be consumed for the next post.
     */
    public function shouldConsumeCreditForNextGeneration(): bool
    {
        return ! $this->hasUnlimitedGenerationAccess()
            && ! $this->hasActiveSubscription()
            && $this->freeGenerationsRemaining() === 0
            && $this->creditBalance() > 0;
    }

    /**
     * Determine whether a given model is available to this user.
     */
    public function canUseModel(string $modelKey): bool
    {
        $availableModels = config('blog.models', []);
        $model = $availableModels[$modelKey] ?? null;

        if (! is_array($model)) {
            return false;
        }

        if (! ($model['subscriber_only'] ?? false)) {
            return true;
        }

        return $this->hasUnlimitedGenerationAccess() || $this->hasActiveSubscription();
    }

    /**
     * Return the model options this user should be allowed to choose from.
     *
     * @return array<string, array<string, mixed>>
     */
    public function availableModels(): array
    {
        return array_filter(
            config('blog.models', []),
            fn (mixed $model, string $modelKey): bool => $this->canUseModel($modelKey),
            ARRAY_FILTER_USE_BOTH
        );
    }

    /**
     * Return the current subscription plan label.
     */
    public function subscriptionPlanLabel(): ?string
    {
        $configuredLabel = config("billing.plans.{$this->subscription_plan}.label");

        if (is_string($configuredLabel) && $configuredLabel !== '') {
            return $configuredLabel;
        }

        return is_string($this->subscription_plan) && $this->subscription_plan !== ''
            ? ucfirst($this->subscription_plan)
            : null;
    }

    /**
     * Determine whether the Stripe customer portal can be opened.
     */
    public function canOpenBillingPortal(): bool
    {
        return filled($this->stripe_customer_id) && filled(config('services.stripe.secret'));
    }

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'generated_posts_count' => 'integer',
            'credit_balance' => 'integer',
            'password' => 'hashed',
            'subscription_ends_at' => 'datetime',
        ];
    }
}
